### ISSUE TITLE
passwordPath not working

### ISSUE THREAD

**Issue by friksa** [kevinsawicki/signcode#1]
Able to sign exe with password property... but when I put it in a separate file and use passwordPath, it fails with this message:

```
Signing failed Signing failed with SIGABRT. Failed to parse PKCS#12 file: /Users/user/Desktop/CERTS/codesign.p12 (Wrong password?)
```

Great project, btw.  Thanks so much!

**Comment by kevinsawicki** [comment]
@friksa are you using an absolute path?

**Comment by kevinsawicki** [comment]
And apologies for the delay in responding to your issue, I didn't see this notification.

**Comment by kevinsawicki** [comment]
@friksa does your password file end in a newline? I think the underlying `osslsigncode` library will error if it does.

**Comment by kevinsawicki** [comment]
I'm going to close this out until I can get more information and/or some reproduction steps and certificates.

I added additional tests for this option and they all are working as expected in the latest release.

As mentioned previously, you might want to check that your password file does not contain a trailing newline which may cause issues.
